name = "AcousticMetrics"
uuid = "046f749b-9c1e-43ca-86bc-6902340f753e"
authors = ["Ingraham, Daniel James (GRC-LTV0) <daniel.j.ingraham@nasa.gov> and contributors"]
version = "0.7.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FLOWMath = "6cb5d3fb-0fe8-4cc2-bd89-9fe0b19a99d3"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"

[compat]
FFTW = "1.4.3"
FLOWMath = "0.3.3, 0.4"
ForwardDiff = "0.10.19"
julia = "1.8.2"
